### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by franksandersen** [Texnomic/JsonViewer#69]
Hi, is it possible to use other methods like Expand, Collapse etc from Blazor Server ? 
I only see the Render method on my JsonViewer instance

**Comment by VirajShah21** [comment]
Having the same issue. Here is a sample of the errors:

```
blazor.server.js:1 [2023-03-27T05:46:02.660Z] Error: Microsoft.JSInterop.JSException: document.querySelector(...).expandAll is not a function
TypeError: document.querySelector(...).expandAll is not a function
    at Object.JsonViewerExpandAll (http://localhost:5111/js/site.js:448:47)
    at http://localhost:5111/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (http://localhost:5111/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (http://localhost:5111/_framework/blazor.server.js:1:75066)
    at Ft._processIncomingData (http://localhost:5111/_framework/blazor.server.js:1:72690)
    at Ft.connection.onreceive (http://localhost:5111/_framework/blazor.server.js:1:67003)
    at i.onmessage (http://localhost:5111/_framework/blazor.server.js:1:51316)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
```
